### ISSUE TITLE
blocked to send using gmail

### ISSUE THREAD

**Issue by LearnedVector** [leemunroe/responsive-html-email-template#100]
I'm getting a message blocked and rejected to send on Gmail. Any work around?

**Comment by leemunroe** [comment]
Can you share a screenshot? Are you using Gmail to send or an ESP?

**Comment by LearnedVector** [comment]
<img width="738" alt="Screen Shot 2019-09-11 at 12 57 51 PM" src="https://user-images.githubusercontent.com/8495552/64722478-299e4f80-d494-11e9-9fd0-97a405f47ef5.png">

Here is a screenshot of some rejection emails. The email did actually start going through once I removed some of the `href` links from the template. not sure why google's rejecting those links.

**Comment by leemunroe** [comment]
I suspect it is because you're trying to send a lot of emails via Gmail. For mass email, or just sending HTML email in general, you want to use a service like SendGrid or Mailchimp. The template you use shouldn't affect this. https://support.google.com/mail/answer/22839?hl=en
