### ISSUE TITLE
Email Width Really Large When in Gmail

### ISSUE THREAD

**Issue by qfaq** [leemunroe/responsive-html-email-template#101]
Hello. 

Whenever I try to paste the code into gmail the width is really large and ugly. How do I fix this?
<img width="972" alt="Screen Shot 2019-09-24 at 4 18 21 PM" src="https://user-images.githubusercontent.com/49662620/65557147-13a67b00-dee7-11e9-88c1-93ef5c4f3721.png">

**Comment by leemunroe** [comment]
Are you sending this with Gmail? What happens if you send it with https://putsmail.com?

**Comment by qfaq** [comment]
It seems to work. However, in my case I'm trying to email my entire class. How would I go at doing this while still doing it from my gmail?

**Comment by leemunroe** [comment]
I see. Gmail isn't really built for sending HTML templates like this. You need to use an ESP like SendGrid, Mailgun or Mailchimp. You might be able to use a [plugin like this](https://www.saleshandy.com/blog/create-send-html-email-template-in-gmail/) but I haven't personally tried it.
