### ISSUE TITLE
Email and email inlined don't match

### ISSUE THREAD

**Issue by mpoiriert** [leemunroe/responsive-html-email-template#105]
I am using a php library to inline the css from the html and I was comparing result.

I spotted that the inlined file in the repository doesn't keep the same structure.

Just look at the
 
<span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>

Just want to point it out.

**Comment by leemunroe** [comment]
Not fully understanding. Can you share a screenshot of what you're seeing vs expected behavior?

**Comment by mpoiriert** [comment]
This is the inlined line for preheader

https://github.com/leemunroe/responsive-html-email-template/blob/44ffa18a7421085dde4edf778116ea4c7736c1cf/email-inlined.html#L105

And this one for the "regular" template:

https://github.com/leemunroe/responsive-html-email-template/blob/44ffa18a7421085dde4edf778116ea4c7736c1cf/email.html#L336

As you can see the regular template the preheader is just after the <body>
And in the inlined it have moved. So the dom structure is not kept in the "css inline" processor.

**Comment by leemunroe** [comment]
Ah you're right. Someone moved it due to an issue with a client.
https://github.com/leemunroe/responsive-html-email-template/commit/4e6e711aad8457b4f005816ff1cae0d7d7fefc42
 I think we can safely move the inlined version too.
