### ISSUE TITLE
Litmus test result link is broken

### ISSUE THREAD

**Issue by gargol** [leemunroe/responsive-html-email-template#107]
When navigating to litmus link from the [readme.md](https://github.com/leemunroe/responsive-html-email-template/blob/master/readme.md#L51) (https://litmus.com/checklist/emails/public/bd7912f) it returns 500

![Screenshot from 2019-11-04 16-41-05](https://user-images.githubusercontent.com/675397/68111549-f28f6c00-ff21-11e9-89c4-d82be520b7ec.png)

**Comment by leemunroe** [comment]
Updated this. Thanks.
https://litmus.com/checklist/emails/public/233ded7
