### ISSUE TITLE
Should Images Always Be Hosted Separately?

### ISSUE THREAD

**Issue by JimTheMan** [leemunroe/responsive-html-email-template#108]
Hi, thanks for making this.

In the README there is an image example where the path is, "https://absolute-path-to-image.jpg". However, it doesn't say anything about this mysterious path. It is possible / recommended to somehow compile the image right into the html file or is hosting your own images the most used method today?

Thanks!

**Comment by leemunroe** [comment]
Yeh you need to host the images somewhere. If you're using an ESP like SendGrid for example, they have a file uploader feature so you would upload then copy the URL of the file. Uploading to S3 would be another alternative or https://cloudinary.com/
