### ISSUE TITLE
Litmus test results URL in Readme doesn't work anymore

### ISSUE THREAD

**Issue by JordyGit** [leemunroe/responsive-html-email-template#118]
In the readme the URL "See the Litmus test results" opens the website, but it hasn't the same results as the screenshot provided in the readme.
The screenshot attached shows what I can see on Litmus.
![ssssss](https://user-images.githubusercontent.com/33500507/79375963-c14bab00-7f59-11ea-8663-7777c45abbc6.png)
Other then that, very nice template, thanks!

**Comment by leemunroe** [comment]
Whoops. Updated. Thanks for heads up. https://litmus.com/checklist/emails/public/233ded7
