### ISSUE TITLE
HTML is not working in forwarded email

### ISSUE THREAD

**Issue by akosijiji** [leemunroe/responsive-html-email-template#120]
Hi, I'm loving this project. But I encountered an issue when I forwarded the email. HTML is not working as expected. Anyone faced this issue? Do you have any workaround to this? Appreciate your response. Thanks!

**Comment by logovitta** [comment]
You don't forward newsletter. Because, depending on the client you use, it may crop important part of the mail. Outlook typically erase the css/responsive part, also adding custom formatting to the text that may alter the graphic you intended.

**Comment by leemunroe** [comment]
Yeh I'm afraid there's nothing can be done about this AFAIK. Forwarding HTML breaks depending on the client.
