### ISSUE TITLE
Customer review cards 

### ISSUE THREAD

**Issue by Charu271** [leemunroe/responsive-html-email-template#122]
#### Review cards are not equal in size. It doesn't look nice

![Screenshot (224)](https://user-images.githubusercontent.com/60181628/82729896-35c3f780-9d19-11ea-8b2d-472fec14148a.png)

**Comment by leemunroe** [comment]
Thanks for feedback! Unrelated to this project so closing the issue but I agree :-)

**Comment by mredbishop** [comment]
:facepalm: this might be one of the weirdest issues I've seen someone take the time to report. Also, I think it looks fine :smile:
