### ISSUE TITLE
Repeated font-family

### ISSUE THREAD

**Issue by willemarcel** [leemunroe/responsive-html-email-template#139]
On the inlined file the font-family rule is repeated in a lot of places inside the table. Is there a reason to that? Wouldn't adding the font-family only on the table html element be enough?

**Comment by leemunroe** [comment]
It uses Juice inliner to inline styles. Goal is to make it bulletproof as each email client behaves in different ways. 

If you've done any testing here and can share, would love to re-evaluate and remove some dups.

**Comment by willemarcel** [comment]
I did a test and we really need to repeat the font-family. Thanks your reply!
