### ISSUE TITLE
`table[class=body]` causes responsive mobile version not working in iOS Gmail 

### ISSUE THREAD

**Issue by danielblazquez** [leemunroe/responsive-html-email-template#148]
It seems that **Gmail for iOS** ignore the `table[class=body]` properties for mobile-friendly styles. 

By removing the atribute selector, the mobile styles work perfectly in this app.

What is this hack used for?

**Comment by leemunroe** [comment]
@danielblazquez do you have a before/after screenshot you can share for context?

**Comment by danielblazquez** [comment]
Here you go

iOS 14.3 Gmail 6.0.2 with `table[class=body]`:
https://user-images.githubusercontent.com/3729461/104575918-dde75180-5657-11eb-8025-f848ca19413c.jpg

Without:
https://user-images.githubusercontent.com/3729461/104575953-e63f8c80-5657-11eb-8400-886c70c59ab8.jpg

**Comment by leemunroe** [comment]
Very helpful thank you! I see what you mean. I tested it without and everything seems fine. I don't recall the original reason for this but it was several years ago. I think we're good to change this.

**Comment by gavin310** [comment]
When you guys say to remove the `table[class=body]` attribute selector, do you mean to change things like `table[class=body] h1 {` to `h1 {` or do you mean to get rid of the "RESPONSIVE AND MOBILE FRIENDLY STYLES" styles all-together?

**Comment by danielblazquez** [comment]
Only the table[class=body]

**Comment by ayushknath** [comment]
Try putting double quotes inside the class value.
Like this:-
table[class="body"]

**Comment by webketje** [comment]
IMO you haven't sufficiently singled out the reason this issue occurs and I think it is because 14 email clients do not support the `[class=body]` CSS3 attribute notation (among them iOS Gmail), as per [CampaignMonitor's CSS reference for email](https://www.campaignmonitor.com/css/selectors/attribute-equals/). 

Changing it to `table.body` will do fine.
