### ISSUE TITLE
No button in Windows Mail or Outlook Office 2019 (Windows 10)

### ISSUE THREAD

**Issue by danielblazquez** [leemunroe/responsive-html-email-template#149]
`email.html` template

### Mail version 16005.13426.20368.0 

![Windows Mail](https://user-images.githubusercontent.com/3729461/104577403-bee9bf00-5659-11eb-8bf2-c95e109b5764.png)

### Outlook 2019
![Outlook](https://user-images.githubusercontent.com/3729461/104579423-3f112400-565c-11eb-9124-c090e9dc9fd1.png)

**Comment by danielblazquez** [comment]
Pull request with fixes
https://github.com/leemunroe/responsive-html-email-template/pull/150

![Windows Mail](https://user-images.githubusercontent.com/3729461/104583663-ae3d4700-5661-11eb-9b05-66dab7bc743e.png)

**Comment by leemunroe** [comment]
Closing as this is resolved when inlining the CSS
https://github.com/leemunroe/responsive-html-email-template#inline-your-css-before-sending
