### ISSUE TITLE
Outlook: the css is not working properly?

### ISSUE THREAD

**Issue by Labritzky** [leemunroe/responsive-html-email-template#155]
Hi, when I send  an email to any email client it's working perfectly but for some reason in outlook it's not responsive and it seems to changes some elements. We've tried inlinine/not inline the css but with no luck. Any tips? 
![ce1](https://user-images.githubusercontent.com/53199201/118503096-4f173e00-b6f8-11eb-895c-4f86b4ea2393.jpg)
![ce2](https://user-images.githubusercontent.com/53199201/118503097-4f173e00-b6f8-11eb-983f-194285b37af0.jpg)

**Comment by leemunroe** [comment]
Hi @Labritzky sorry for the slow followup. This may be too late but could you confirm what Outlook version and OS? And could you share the HTML you're sending? That'll allow me to test and inspect the HTML. Thanks.

**Comment by gsg-chris** [comment]
I can confirm this issue in Outlook. When viewed using using a online web email system, it displays correctly.

It used to work fine, but Microsoft changed something... of course.

Windows 10 Pro. Most recent version of Outlook.

**Comment by webketje** [comment]
Might be related: https://github.com/leemunroe/responsive-html-email-template/pull/126#issuecomment-931200386
@gsg-chris could you try setting width: 100% as mentioned in the comment linked above?

**Comment by leemunroe** [comment]
Should be resolved in latest update but let me know if you see otherwise
https://litmus.com/checklist/emails/public/wq72nfDD20xilrrW
