### ISSUE TITLE
Where should I include the license notice ?

### ISSUE THREAD

**Issue by recser** [leemunroe/responsive-html-email-template#166]
Hi, maybe stupid question but should the license notice be included in the source code of the project or added to emails sent with this template ? 

Best regards,

**Comment by webketje** [comment]
> "The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

The software in this case is an "Email template repository", not the email derivatives you create from it. 
So if you fork the project, you should keep the MIT license in the source code repository only.

**Comment by recser** [comment]
@webketje got it. thank you for taking the time to answer ;)
