### ISSUE TITLE
other style in gmail in browser

### ISSUE THREAD

**Issue by andylaci** [leemunroe/responsive-html-email-template#17]
hello, the template is behaving strange on gmail in browser, the background is white, not gray. Is it bug or feature ? :D

**Comment by IdemIsDito** [comment]
Had the same problem, but reading the docs learned me that some e-mail clients need inline CSS. You should use the email-premailer.html file instead.

**Comment by misawsneto** [comment]
Yep, 

gmail problems here
![untitled](https://cloud.githubusercontent.com/assets/1959468/6813078/8429e224-d251-11e4-9e4c-4335218f3c0b.png)

**Comment by leemunroe** [comment]
@misawsneto Is that using inlined CSS? Can you share the HTML you're sending?

**Comment by leemunroe** [comment]
You're right. Needed background color applied to the table. Pushed a fix.

![image](https://cloud.githubusercontent.com/assets/15963/7465291/61c64e74-f282-11e4-98fe-eec62584b936.png)
