### ISSUE TITLE
Fun: Unsubscribe gif link is broken

### ISSUE THREAD

**Issue by EncryptEx** [leemunroe/responsive-html-email-template#171]
I was messing up with the template when I came across the link to a gif, but it's broken. 
Since I'm a little bit curious about what was it, I'll open this thread to discuss the new one 😉😉

Exact line can be found here: https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L392

Btw, this is not a real code issue.

**Comment by YashwanthLakkimsetti** [comment]
can you please elaborate on this issue? So, I can look into it?

**Comment by leemunroe** [comment]
Ah [this line](https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L387) — was just a link to a silly gif. You should replace this with your ESPs unsubscribe link.

**Comment by YashwanthLakkimsetti** [comment]
Is it completed??
