### ISSUE TITLE
Social icons in footer addition

### ISSUE THREAD

**Issue by proofrating** [leemunroe/responsive-html-email-template#172]
How would I add social icons in the footer?

**Comment by YashwanthLakkimsetti** [comment]
Can you assign this issue to me? I can resolve it.

**Comment by YashwanthLakkimsetti** [comment]
Which social icons do you need like Facebook, twitter, youtube is fine?

**Comment by proofrating** [comment]
Facebook, twitter, instagram and LinkedIn

**Comment by YashwanthLakkimsetti** [comment]
![image](https://user-images.githubusercontent.com/96442644/192951027-ce359887-b419-4590-9d35-85a47d0cc259.png)
Is this fine or I should make any changes?

**Comment by proofrating** [comment]
I was thinking just the icon no background and the grey color like the footer wording.  Where you can adjust the size of the icon if needed

**Comment by YashwanthLakkimsetti** [comment]
Can we get on a call and can we discuss it tomorrow? Is it fine?

**Comment by Vrajjangid5** [comment]
Can you assign this issue to me? I can resolve it.

**Comment by YashwanthLakkimsetti** [comment]
Already it was assigned to me

**Comment by proofrating** [comment]
Was it added?  Just want the icons grey

**Comment by proofrating** [comment]
Any update?


Jonathan Smith

Creator @ Proofratings

***@***.*** ·  https://proofratings.com















---- On Tue, 04 Oct 2022 06:37:09 -0400 Jonathan Smith ***@***.***> wrote ---



Was it added?  Just want the icons grey 


On Sep 30, 2022, 12:57 AM -0400, YashwanthLakkimsetti ***@***.***>, wrote:
 





Already it was assigned to me

**Comment by proofrating** [comment]
Anything updated on it?

**Comment by leemunroe** [comment]
@YashwanthLakkimsetti great to see you helping @proofrating with this.

I wanted to add some clarity to this thread, the social icons are outside of the scope of the goals of this repo. So I'd prefer to not have this committed here directly and instead have this live in a fork (or even outside GitHub if you prefer). This shouldn't block anything, just making sure expectations are set.

**Comment by proofrating** [comment]
Of course.  If you can just provide me the snippet of code to add and where, I can just add it on my end for the use case

**Comment by proofrating** [comment]
???


Jonathan Smith

Creator @ Proofratings

***@***.*** ·  https://proofratings.com















---- On Tue, 11 Oct 2022 10:58:15 -0400 Jonathan Smith ***@***.***> wrote ---



Of course.  If you can just provide me the snippet of code to add and where, I can just add it on my end for the use case


On Oct 11, 2022, 10:53 AM -0400, Lee Munroe ***@***.***>, wrote:
 





https://github.com/YashwanthLakkimsetti great to see you helping https://github.com/proofrating with this.

I wanted to add some clarity to this thread, the social icons are outside of the scope of the goals of this repo. So I'd prefer to not have this committed here directly and instead have this live in a fork (or even outside GitHub if you prefer). This shouldn't block anything, just making sure expectations are set.

**Comment by proofrating** [comment]
Anyone on this?

**Comment by proofrating** [comment]
> Can you assign this issue to me? I can resolve it.

@YashwanthLakkimsetti can you help me on this?  Please email me privately jsmith@proofratings.com

**Comment by proofrating** [comment]
> Can you assign this issue to me? I can resolve it.

@Vrajjangid5 if you can help me on this please email me privately jsmith@proofratings.com
