### ISSUE TITLE
Inlined version CSS problems on the Gmail mobile app for both iOS and Android

### ISSUE THREAD

**Issue by noe** [leemunroe/responsive-html-email-template#178]
The [email-inlined.html](https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html) file is not shown properly for me on the Gmail app for both iOS 16.3 and Android 10. Specifically, some CSS is ignored, like `border-radius` on the outer container table or `font-size`:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/4972/217966766-0e105c2c-378a-4960-8982-5e66090799bb.png">

However, when inlining with the [MailChimp inlining tool](https://templates.mailchimp.com/resources/inline-css/), it is shown properly:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/4972/217966890-028052fe-248e-4362-ba9b-bc25462f1c6b.png">

**Comment by leemunroe** [comment]
This should be working with the latest update that was pushed. But let me know if you see something different.
https://litmus.com/checklist/emails/public/wq72nfDD20xilrrW
