### ISSUE TITLE
Missing css classes

### ISSUE THREAD

**Issue by rabol** [leemunroe/responsive-html-email-template#194]
Hi

The inlined template is missing the following css class:

preheader, wrapper

**Comment by leemunroe** [comment]
Hi @rabol 

The preheader and wrapper styles are inlined. The wrapper has embedded responsive styles. Could you point out what exactly you're not seeing that you expected?

Here are the lines:

- wrapper CSS https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html#L25
- wrapper HTML https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html#L103
- preheader HTML https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html#L98
