### ISSUE TITLE
how to modify width on desktop?...

### ISSUE THREAD

**Issue by erikdemarco** [leemunroe/responsive-html-email-template#196]
how to modify width on desktop? because with wide screen lcd display the content box looks so slim viewed on desktop

**Comment by leemunroe** [comment]
Hey @erikdemarco 

There is a width and max-width you can play with.
https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L53
https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L60

This goes with 600px by default as it's pretty safe but you could definitely go for larger.
