### ISSUE TITLE
Outlook 2013 uses Times New Roman instead of the font-family value

### ISSUE THREAD

**Issue by banzaimachine** [leemunroe/responsive-html-email-template#20]
I tried some styling but i can't get it to work as i wish.
Is there a fix for this Outlook behaviour?

**Comment by leemunroe** [comment]
@banzaimachine I couldn't reproduce. Although I am using Litmus to test rather than the real thing. Are you using the inlined version?

![image](https://cloud.githubusercontent.com/assets/15963/7465201/313a4dd8-f281-11e4-9489-055d954e7197.png)

**Comment by banzaimachine** [comment]
Yes, I tested it on the updated Office 2013 and it was displaying in Times New Roman.
Office 2011 displayed it correctly though.

However, I thank you for the answer but given that I was in a hurry i ended up using another template.

(sorry for my engrish)
