### ISSUE TITLE
Can you give a example of template with image

### ISSUE THREAD

**Issue by Jakezheng** [leemunroe/responsive-html-email-template#22]
Can you give a example of template with image

**Comment by leemunroe** [comment]
Is there something specific you're looking for? What happens when you include an image currently?

e.g. `<p><img src="" alt="" width="" height=""></p>`

**Comment by yaronguez** [comment]
Adding a large image seems to break the responsiveness.  Should the image go within a <td> ?

**Comment by yaronguez** [comment]
I think I've resolved it but haven't test it in a mail client.  Changing the img styling from:
```
img { 
    max-width: 100%; 
}
```
to 
``` 
img {
    width: 100%;
    max-width: 600px;
}
```
seems to the do trick.

**Comment by leemunroe** [comment]
Nice! @yaronguez Want to submit a PR and I'll merge it in?

**Comment by yaronguez** [comment]
Sure thing!  https://github.com/leemunroe/responsive-html-email-template/pull/25

**Comment by thilinag** [comment]
The problem is smaller images will also stretch to 100% if you do this.

**Comment by borzaka** [comment]
Add `img-responsive` class to the full width image to became responsive, and maintain aspect ratio.
