### ISSUE TITLE
Centering buttons?

### ISSUE THREAD

**Issue by opheliadesign** [leemunroe/responsive-html-email-template#26]
What is the recommended method to center a `btn-primary` link button? The current code uses a nested table to create the button, previously I simply used something along these lines:

```
<tr>
<td align="center">
    <a href="#" class="btn-primary">Link..</a>
</td>
</tr>
```

**Comment by leemunroe** [comment]
I think the ideal solution is another table that wraps it and applies alignment.

```
<table width="100%"><tr><td align="center">
            <table class="btn-primary" ...
```

Discovered that using a table for the button is a bit more bulletproof across certain clients, particularly Outlook.
