### ISSUE TITLE
E-mail template not rendering correctly in Gmail web client

### ISSUE THREAD

**Issue by janyksteenbeek** [leemunroe/responsive-html-email-template#28]
I have been using your email template for over a week now, and just tried it out by sending it to an Gmail email account. However, the email template does not get rendered correctly in the web client of Gmail (www.gmail.com) as you can see on the screenshot below

You can find the email (including headers) [here](https://gist.github.com/janyksteenbeek/5c8784cef4c538e346c7). I am using Mailjet to get the e-mail delivered, and Laravel to send the e-mail.

![7bb6b0e](https://cloud.githubusercontent.com/assets/3578636/9900309/21f33454-5c60-11e5-884f-9d9db57151de.png)

**Comment by leemunroe** [comment]
Hi @janyksteenbeek you need to inline the CSS before sending, as Gmail strips any CSS that isn't inlined. You can do the inlining yourself, or use the `email-inlined.html` file.

**Comment by janyksteenbeek** [comment]
Thanks @leemunroe, that worked perfectly fine!
