### ISSUE TITLE
inliner

### ISSUE THREAD

**Issue by teslaji** [leemunroe/responsive-html-email-template#29]
can you tell me which inliner processor you used to generate html-inlined.
I have some changes in body and your inlined version is not much readable.

**Comment by leemunroe** [comment]
I used [Zurb](http://zurb.com/ink/inliner.php) for this. Although on production projects I'll often use Premailer or Juice.

**Comment by jonscottclark** [comment]
+1 for Juice!

Like Premailer and Zurb Ink, Juice has a web version that also allows you to set a lot of different options: http://automattic.github.io/juice/

Here's how I use Juice in a `gulp` workflow:

```js
var mapStream = require('map-stream');
var juice = require('juice');

gulp.task('inline-email', function() {
  // Juice options
  var options = {
    preserveMediaQueries: true,
    preserveImportant: true,
    webResources: {
      images: false
    }
  };

  return gulp.src('src/email*.html')
    .pipe(mapStream(function(file, done) => {
      var basename = path.basename(file.path);
      var target = path.join('dist', basename);
      juice.juiceFile(file.path, options, function(err, html) => {
        fs.writeFileSync(target, '');
        fs.appendFileSync(target, html);
      });
      done();
    }));
});
```
