### ISSUE TITLE
Typo: Margin instead of margin

### ISSUE THREAD

**Issue by jtammen** [leemunroe/responsive-html-email-template#32]
This seems to confuse the CSS inliner I was using.

See https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L156

**Comment by leemunroe** [comment]
This is actually on purpose as a hack for Outlook and Outlook.com
https://litmus.com/community/discussions/84-what-s-your-favorite-hack#comment-2135

What inliner are you using?

**Comment by jtammen** [comment]
Oh, my bad!

I use https://github.com/jonkemp/gulp-inline-css which relies on https://github.com/jonkemp/inline-css.

I just noticed that – in the browser – the container is not centered anymore after running the inliner. But maybe I can just ignore that…
