### ISSUE TITLE
Gmail Webclient problem with provided email-inlined.html

### ISSUE THREAD

**Issue by mgraupner** [leemunroe/responsive-html-email-template#37]
Using your provided email-inlined.html (unmodified!) I can't get a satisfying result for Gmail Webclient. See the following screenshot. Is this a known limitation? Things not working: Not centered container, missing background color.

![bildschirmfoto 2016-03-07 um 16 06 19](https://cloud.githubusercontent.com/assets/586644/13573170/997e40d0-e47e-11e5-8333-ba4ff7cfe426.png)

**Comment by invalidusernam3** [comment]
+1 styling breaks completely in gmail

**Comment by mgraupner** [comment]
@invalidusernam3 @leemunroe  I came up with a solution that creates a valid result with Premailer, when using the original email.html with [the Mailchimp Inliner](http://templates.mailchimp.com/resources/inline-css/) everything works as expected. So I guess it's Premailers fault here.

**Comment by leemunroe** [comment]
I wasn't able to reproduce. I copy/pasted the inlined version, sent it to Gmail and this is what I see.

![image](https://cloud.githubusercontent.com/assets/15963/13659825/a4d99954-e639-11e5-9327-d8b5184eb809.png)

@mgraupner Odd. What browser are you using?

**Comment by mgraupner** [comment]
@leemunroe Client: Firefox 45 on Mac OS X 10.11.3. Same for Chrome 50.0.2661.11 dev (64-bit) on Mac OS.

I guess it's a client thing, same issue occuring in https://github.com/mailgun/transactional-email-templates/issues/20

**Comment by Temeez** [comment]
I have the same problem with Firefox 47.0.1 on Windows 7.

**Comment by leemunroe** [comment]
Here's an updated version that I'll be merging soon. Please check this version out and see if it fixes the problem for you. Also welcome to any other getting started feedback.

https://github.com/leemunroe/responsive-html-email-template/pull/41

**Comment by leemunroe** [comment]
Merged and released v1.0.0
https://github.com/leemunroe/responsive-html-email-template/releases/tag/v1.0.0

Please verify if these improvements have fixed the problems you've highlighted. Thanks.

**Comment by leemunroe** [comment]
@Temeez @mgraupner Did you try out the latest? Curious if that helps fix things for you.

**Comment by mgraupner** [comment]
@leemunroe Didn't have time to try the new version yet, will do as soon as possible and let you know.
