### ISSUE TITLE
Breaks in Google Inbox.

### ISSUE THREAD

**Issue by rankun203** [leemunroe/responsive-html-email-template#40]
![image](https://cloud.githubusercontent.com/assets/2988555/16415035/c271aaa2-3d6d-11e6-9d22-be94c78ca179.png)

Seems Inbox separate the page into parts by table.

**Comment by leemunroe** [comment]
Hmm I'm not seeing the same thing. Can you try resending a new email to yourself and confirm?

![image](https://cloud.githubusercontent.com/assets/15963/16524210/21b21334-3f9f-11e6-986d-66c11c4a0f85.png)

And maybe include the full MIME to look at. Thanks.

**Comment by artforlife** [comment]
Works well for me in Gmail. I am sending using NodeJS and Nodemailer.

**Comment by andreynering** [comment]
Happened for me also, but I found the reason:

Inbox tries to group emails from a common sender (so called conversation view), and tries to hide a common signature if exists.

The email was "fixed" after I deleted old messages, including from trash.

I don't know if there's a way to prevent that.
