### ISSUE TITLE
Desktop view missing button

### ISSUE THREAD

**Issue by tkwon** [leemunroe/responsive-html-email-template#44]
Looks fine on mobile and tablet. But when opened with Firefox and MS Edge using Gmail the link shows up as plain text:

![screen shot 09-05-16 at 11 42 pm](https://cloud.githubusercontent.com/assets/311161/18264025/9807edae-73c2-11e6-9f87-c70063197986.PNG)

**Comment by leemunroe** [comment]
Thanks @tkwon. Trying to reproduce. Can you show me the full HTML you're sending? And to confirm, using latest Firefox in Gmail?

**Comment by tkwon** [comment]
I cut and paste directly from your email.html. I'm attaching a copy for your review.

I used Firefox 48.02 as well as Microsoft Edge 25.10586.

Unfortunately I can't get Chrome to run on my computer due to other issues.

I did verify the email works fine on desktop using GoDaddy email. So it seems to be related to Gmail.
[email_confirm.txt](https://github.com/leemunroe/responsive-html-email-template/files/457176/email_confirm.txt)

**Comment by tkwon** [comment]
FYI, I also found out the button doesn't appear when using mail from zoho.com

**Comment by leemunroe** [comment]
Are you inlining the CSS before sending? You either need to use the template that is inlined `email-inlined.html` or your ESP needs to inline your CSS for you before sending.

https://github.com/leemunroe/responsive-html-email-template#sending-emails-using-a-marketing-service-like-campaign-monitor-or-mailchimp

**Comment by tkwon** [comment]
Ok thats most likely the problem. I'm using django fyi and sending the email myself.

**Comment by leemunroe** [comment]
Ah gotcha. I'm not familiar with django but try [this](https://github.com/roverdotcom/django-inlinecss).
