### ISSUE TITLE
CSS issue?

### ISSUE THREAD

**Issue by tkwon** [leemunroe/responsive-html-email-template#45]
Sorry for another issue but I was able to get things working using the django-inlinecss library you pointed out. However, when using it I found the resulting button has a table td around it that appears too big. (or the button is too small). Here's a screenshot as I hover over the buton.

![screen shot 09-06-16 at 10 00 pm](https://cloud.githubusercontent.com/assets/311161/18300430/d725c1b2-747d-11e6-9b0d-c047df7a94cf.PNG)

When I remove 

.btn-primary table td { background-color: #3498db; }

I now get: 

![screen shot 09-06-16 at 10 01 pm](https://cloud.githubusercontent.com/assets/311161/18300438/eeaf7454-747d-11e6-8a22-87a29d6ae13a.PNG)

These are both on a GoDaddy account although I see issues on mobile as well (but not as bad)

**Comment by leemunroe** [comment]
I'm having trouble reproducing this. Can you take a straight copy of the [inlined version here](https://raw.githubusercontent.com/leemunroe/responsive-html-email-template/master/email-inlined.html) and see if this has the same issue. If so, please share the screenshot.

And no problem re. the issue, if you find something then keep them coming. Happy to make sure this works.

**Comment by tkwon** [comment]
Your inlined version works fine. It must be the django inliner is doing something incorrectly.
