### ISSUE TITLE
Width at Outllook 2016

### ISSUE THREAD

**Issue by inpq** [leemunroe/responsive-html-email-template#47]
Hello
I'm testing the template in different mail clients.
In all programs it looks good, but not with Outlook 2016.
Shown in a narrow column and with the buttons unformatted

I do not know how to correct this
Thanks.

**Comment by leemunroe** [comment]
Thanks for the report. Can you send a screenshot? And is it a straight copy/paste of the code you're testing?

**Comment by inpq** [comment]
Thanks for the reply

I attach a screenshot and an html file with the email code.

 

Thanks.

 

De: Lee Munroe [mailto:notifications@github.com] 
Enviado el: viernes, 11 de noviembre de 2016 0:52
Para: leemunroe/responsive-html-email-template <responsive-html-email-template@noreply.github.com>
CC: inpq <info@inpq.com>; Author <author@noreply.github.com>
Asunto: Re: [leemunroe/responsive-html-email-template] With at Outllook 2016 (#47)

 

Thanks for the report. Can you send a screenshot? And is it a straight copy/paste of the code you're testing?

**Comment by inpq** [comment]
![email](https://cloud.githubusercontent.com/assets/1485896/20208676/250b1b8e-a7f0-11e6-9845-7f81ae3327c9.png)

**Comment by inpq** [comment]
[_email_send.txt](https://github.com/leemunroe/responsive-html-email-template/files/585305/_email_send.txt)

**Comment by leemunroe** [comment]
Ah, are you inlining the CSS before sending?

https://github.com/leemunroe/responsive-html-email-template#sending-emails-directly-from-your-app-or-using-a-developer-service

**Comment by inpq** [comment]
I use https://github.com/scottrobertson/premailer
[_email_send.txt](https://github.com/leemunroe/responsive-html-email-template/files/588729/_email_send.txt)
Thanks!

**Comment by inpq** [comment]
![email](https://cloud.githubusercontent.com/assets/1485896/20258987/af022058-aa52-11e6-9589-62757f0c7753.png)
[_email_send.txt](https://github.com/leemunroe/responsive-html-email-template/files/588796/_email_send.txt)

Now the buttons look good, but the width still goes wrong

Thanks

**Comment by alambrecht** [comment]
+1 I am having the same issue.

**Comment by leemunroe** [comment]
Is this happening when you test the original inlined email here?

https://raw.githubusercontent.com/leemunroe/responsive-html-email-template/master/email-inlined.html

**Comment by inpq** [comment]
With that goes well.
Thanks!

**Comment by arun-is** [comment]
I'm having the same issue as well. I diffed the above inlined email and one I produced by inlining your original email in premailer and there are many differences

**Comment by leemunroe** [comment]
Just want to check we're all on the same page here before digging more in to this.

Are you having issues with the original email template [here](https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html). With the email that @inpq provided [above](https://github.com/leemunroe/responsive-html-email-template/issues/47#issuecomment-260284110)? Or with your own version of the email?

Attempting to isolate the source of the problem. Whether it's with the original email templates, or with a specific inliner, or human error.

**Comment by arun-is** [comment]
I took your original non-inlined email, inlined it using premailer and dropped it into litmus. I noticed the same width issues as seen above.

**Comment by leemunroe** [comment]
Gotcha. Thanks, taking a look.

**Comment by leemunroe** [comment]
Hmm ok I see what you mean. I tried inlining with Premailer and got the same results.

When I tried inlining with Putsmail it worked fine.

Need to dig deeper to see where this breaks down but in the mean time I recommend using another inliner like [Putsmail](https://putsmail.com/inliner). Other options are [Roadie](https://github.com/Mange/roadie) and [Juice](https://github.com/Automattic/juice).

![image](https://cloud.githubusercontent.com/assets/15963/20734378/e1efe8a4-b64d-11e6-9d2a-147f0ae8f380.png)

**Comment by arun-is** [comment]
Thanks for digging into this and a bigger thanks for developing this template.

**Comment by inpq** [comment]
Thanks for the development!

**Comment by oliversalzburg** [comment]
I'm running the template through Juice, but I'm seeing the same width issue as reported on this thread.

**Comment by oliversalzburg** [comment]
When I remove https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L52 everything looks fine, at least in Outlook 2016 :P

**Comment by leemunroe** [comment]
That could be it. Do you have a link to Litmus or screenshot? 

This is when I wish I had documented why each line of CSS had been added as there was a reason for having it at some stage :)

**Comment by oliversalzburg** [comment]
@leemunroe The original looked exactly line @inpq's screenshot. When I removed the line I mentioned, the result looks exactly like the Litmus shots linked in the README.

I already moved on from there, so I don't have anything I can contribute right now :(

Thanks for the template!

**Comment by leemunroe** [comment]
Thanks all for your help debugging this. 

@Devaney's PR fixed it and I uploaded a new inlined version.
