### ISSUE TITLE
Use of Margin intentional?

### ISSUE THREAD

**Issue by oliversalzburg** [leemunroe/responsive-html-email-template#49]
I see several uses of `Margin` (notice the uppercase `M`) in the template. Is that intentional?

**Comment by leemunroe** [comment]
Yes. It was a hack as some clients ignored lower case M. While it has been a while since I vigorously tested this `Margin` doesn't seem to be an issue.

**Comment by oliversalzburg** [comment]
Interesting. My IDE complained about it, so I changed them to lower-case and everything still looks fine (...in the 2 clients I tested with :P)
