### ISSUE TITLE
<meta charset="utf-8">

### ISSUE THREAD

**Issue by stevenvachon** [leemunroe/responsive-html-email-template#50]
Is this safe? It's shorter and nicer.

**Comment by xorinzor** [comment]
I don't really see why this would matter, those few bytes wouldn't really make much of a difference.

**Comment by stevenvachon** [comment]
They do when sending millions of emails.

**Comment by leemunroe** [comment]
@stevenvachon How's this working out? I haven't tested this at scale. Would love to know if there are any issues.
