### ISSUE TITLE
Why does <h1> force text-transform uppercase?

### ISSUE THREAD

**Issue by galengidman** [leemunroe/responsive-html-email-template#55]
Is this in place because it serves as some kind of compatibility hack I'm not aware of? If not, it seems like title capitalization should be left to content producers instead of being forced by CSS.

This is especially troublesome when working with titles that have words that _should_ begin with a lowercase letter. Examples:

- `jQuery` → `JQuery` (incorrect)
- `Have a Nice Day` → `Have A Nice Day` (incorrect)

**Comment by leemunroe** [comment]
@galengidman No hack. Just opinionated. I see your issue. I would say treat this template like a boilerplate and make your changes.

**Comment by galengidman** [comment]
Gotcha — appreciate the update.

I'd highly suggest changing this, but obviously it's your call. Thanks for the nice template.
