### ISSUE TITLE
Missing padding in Outlook

### ISSUE THREAD

**Issue by siliconforks** [leemunroe/responsive-html-email-template#56]
In most clients there is 10px padding between the main content area (white background) and footer (3 lines at the bottom), but in Outlook this seems to be missing.  This can be seen at https://litmus.com/checklist/emails/public/d432046 with the following clients:

* Outlook 2007 - Win 7
* Outlook 2013 - Win 7
* Outlook 2013 120 DPI - Win 7
* Outlook 2016 - Win 7

Presumably this is because Outlook does not support padding on the div element (according to https://www.campaignmonitor.com/css/).

**Comment by leemunroe** [comment]
@siliconforks You're right. For a quick fix, add some padding to the first `<td>` in the footer and remove the padding from the div. That should work. I'll update the repo once I've tested it a bit more.

**Comment by scyclops** [comment]
Has there been any update on this?

**Comment by leemunroe** [comment]
Should be fixed in latest master. Missing the class that adds padding to the block.

https://github.com/leemunroe/responsive-html-email-template/releases
