### ISSUE TITLE
Button not showing in mailbbox

### ISSUE THREAD

**Issue by deveshkrsingh** [leemunroe/responsive-html-email-template#57]
Buttons are not showing in mail,it is coming as hyperlink
![capture](https://cloud.githubusercontent.com/assets/5374728/23721851/2fbb256a-0411-11e7-9644-909b08fbe932.PNG)

**Comment by leemunroe** [comment]
@deveshkrsingh Can you share the code you're using and I'll try and reproduce? Just to double check, are you inlining the CSS before sending? https://github.com/leemunroe/responsive-html-email-template#sending-emails-directly-from-your-app-or-using-a-developer-service
