### ISSUE TITLE
does not render properly in Outlook 2013.

### ISSUE THREAD

**Issue by shawnpj** [leemunroe/responsive-html-email-template#58]
i just did a test and it does not render properly in outlook 2013.  the entire column appears to the right when open in email test.  It is not in the center of the screen when you open an email.  It does look good in yahoo mail, iOS and so on.  How can I fix it?

**Comment by leemunroe** [comment]
Hi @shawnpj can you share the html you're testing? And also a screenshot?

Here is what I see when I take `email-inlined.html` and paste it into Litmus to preview. Which looks ok to me.

https://litmus.com/checklist/emails/public/29513bd

**Comment by shawnpj** [comment]
hi.. here is the preview screenshot that was taken in Outlook 2013 and html file.

Not sure why the Call to Action looks different.

![banner_placeholder](https://cloud.githubusercontent.com/assets/10515121/24865351/fd6b11c8-1dd4-11e7-8774-397741b66f0a.jpg)
![image_placeholder](https://cloud.githubusercontent.com/assets/10515121/24865350/fd678fee-1dd4-11e7-82c4-7a450caca383.jpg)
![preview-test](https://cloud.githubusercontent.com/assets/10515121/24865352/fd9894f4-1dd4-11e7-9b5e-f02ba6c202da.jpg)
[responsive.zip](https://github.com/leemunroe/responsive-html-email-template/files/910298/responsive.zip)

**Comment by shawnpj** [comment]
here is another screenshot taken from the browser.

![preview-test 2](https://cloud.githubusercontent.com/assets/10515121/24866791/3bc9381a-1dd9-11e7-923f-52b1bb79cd1f.jpg)

**Comment by leemunroe** [comment]
Thanks @shawnpj. Are you inlining the CSS as [described here](https://github.com/leemunroe/responsive-html-email-template#sending-emails-directly-from-your-app-or-using-a-developer-service) before sending? The HTML you attached did not have CSS inlined.

**Comment by shawnpj** [comment]
here is the inline version.

[responsive-inliner.zip](https://github.com/leemunroe/responsive-html-email-template/files/920474/responsive-inliner.zip)

**Comment by leemunroe** [comment]
@shawnpj Can you check latest master? All looking good from my side.

https://github.com/leemunroe/responsive-html-email-template/releases
