### ISSUE TITLE
Doesn't render properly in Spark MacOS

### ISSUE THREAD

**Issue by mxmzb** [leemunroe/responsive-html-email-template#62]
Only in [MacOS Spark](https://itunes.apple.com/app/id1176895641?mt=12) styles seem not to apply, on the iOS app it seems to work fine though...

**Comment by leemunroe** [comment]
Interesting. Haven't used it before. Do you know what rendering engine it is using? Is this the only client you're having issues with?

**Comment by mxmzb** [comment]
I am afraid I don't know the engine they use on that. However, it seems this is the only client with this issue for me, yes.

**Comment by ViggoV** [comment]
I think that this is a problem with Spark for Mac. I have the same issue, but if I press reply or forward, the referenced mail will be styles..

**Comment by mxmzb** [comment]
@ViggoV doesn't display for me correctly even if I reply / forward.

**Comment by leemunroe** [comment]
@mxmzb Mind sharing a screenshot to help me troubleshoot?

**Comment by mxmzb** [comment]
i think this was my bad, it wasn't the inline css version but it was with stylesheets. i didn't try if it works with inline version since then, but i am pretty sure that this was the reason. sorry for that!

**Comment by leemunroe** [comment]
@mxmzb No problem thanks for following up
