### ISSUE TITLE
Forward clears <head>

### ISSUE THREAD

**Issue by mfoote** [leemunroe/responsive-html-email-template#66]
When you forward an email it wipes out the formatting.

**Comment by leemunroe** [comment]
@mfoote Unfortunately there's little that can be done about forwarding. [Here's a good post from Litmus](https://litmus.com/blog/when-forwarded-emails-break). 

That said, in your issue you mention it clearing `<head>`. If you have your CSS inlined then this should have minimal effect. What does your original code look like that you're sending? And what client are you testing?
