### ISSUE TITLE
Interesting complaints at http://www.accessible-email.org

### ISSUE THREAD

**Issue by ghenry** [leemunroe/responsive-html-email-template#67]
Issues valid?

[http://www.accessible-email.org/](http://www.accessible-email.org/)

No lang set, no header etc.

Thanks.

**Comment by ghenry** [comment]
It also wants to add `role="presentation"`  to the tables.

**Comment by leemunroe** [comment]
The `role` attribute on tables and `lang` are good points. We could add those.
