### ISSUE TITLE
Capital M margins

### ISSUE THREAD

**Issue by noman-land** [leemunroe/responsive-html-email-template#68]
This is more of a question than an issue but I was wondering why only _some_ of the margins in the template are capital M. I understand it's best practice to use capital margins because Outlook for some reason doesn't strip out margins of there's a capital letter in the declaration. Were some of the margins left lowercase for some specific purpose or should they all be capitalized?

**Comment by leemunroe** [comment]
@noman-land Good question. Probably what happened was when I put this together I used lower case m for everything, then noticed it didn't display well in Outlook.com so I added the fix where it mattered.

As of current day, I don't think you need this hack any more for Outlook.com. I haven't tested this myself but have read it on [different articles](https://www.emailonacid.com/blog/article/email-development/tips_and_tricks_outlook.com). 

If someone can verify with a screenshot we should update the code.

**Comment by leemunroe** [comment]
Resolved.
