### ISSUE TITLE
Content not centered on Mac OS Mail

### ISSUE THREAD

**Issue by idiazroncero** [leemunroe/responsive-html-email-template#74]
Hello!
First of all, thanks for your amazing work.
I am having some issues with centering on Mail on Mac (High Sierra, 10.13.4).
I'm sending the HTML inlined version, copy & paste, and the content is not centered. I have checked the source and it's the same as the original:

<img width="814" alt="captura de pantalla 2018-05-21 a las 12 55 49" src="https://user-images.githubusercontent.com/3958741/40304326-a59ff10e-5cf6-11e8-90b8-21a67bad075c.png">

Any ideas?

**Comment by leemunroe** [comment]
Thanks @idiazroncero. What are you using to send the HTML? I just checked Litmus and my own client and looks fine.

![image](https://user-images.githubusercontent.com/15963/40335613-7461d8be-5d19-11e8-9682-a429662cd4c2.png)

![image](https://user-images.githubusercontent.com/15963/40335707-f0ef08b6-5d19-11e8-8f1b-f6f178d92157.png)

**Comment by leemunroe** [comment]
@idiazroncero Were you able to get this working? If so I'll close the issue.

**Comment by idiazroncero** [comment]
Nop, but I guess is something on my side. I'm using Drupal (and theoretically a template that doesn't alter the code) and Sparkpost... so yes, there is a lot of middleware, I have to take a look.

**Comment by reense** [comment]
Same thing is happening here.

**Comment by pziewiec** [comment]
The same problem if I use juice with removeStyleTags = true (default value).

**Comment by leemunroe** [comment]
@pziewiec Can you share your code so I can troubleshoot?

**Comment by pziewiec** [comment]
I checked twice - problem is with html fitler in ckeditor not juice. Running juice on html from repository - email looks good.

**Comment by leemunroe** [comment]
I see. Not familiar with ckeditor. Is this desktop editor or integrated into a web service or ESP? Do you know what ckeditor is stripping? I wonder if something similar is happening the other people above.

**Comment by pziewiec** [comment]
ckeditor has no fullPage=true, so strip tags: html, head, body
[email-after-ckeditor.html.zip](https://github.com/leemunroe/responsive-html-email-template/files/2225161/email-after-ckeditor.html.zip)

**Comment by idiazroncero** [comment]
@leemunroe Ckeditor is a wysiwyg text editor, one of the most popular, used on many CMSs including Drupal and it provides a huge degree of sanitization so yes, it seems like it could be the source of this issue.

**Comment by leemunroe** [comment]
Got it. Thanks for the follow up. Closing.
