### ISSUE TITLE
Button issue with Outlook on Android

### ISSUE THREAD

**Issue by dlancea** [leemunroe/responsive-html-email-template#76]
It seems there's an issue with the .btn (and/or .btn-primary) class when viewing the email in Outlook on Android.

The text does not return to white on Android's version of Outlook. Also, the bottom border-radius does not match the top.

This is using the exact code from the current email.html.

![Screenshot](https://user-images.githubusercontent.com/227576/45834273-b759bb80-bcd4-11e8-9224-caab840658b3.png)

**Comment by dlancea** [comment]
The workaround for the text color is to include an inline style for white text in the anchor tag:

`<a href="{{ url }}" style="color: #FFFFFF">Button text</a>`

**Comment by leemunroe** [comment]
@dlancea Thanks! Will update soon. Or feel free to submit PR.

**Comment by leemunroe** [comment]
Is this still an issue? I wasn't able to reproduce. Closing but feel free to correct me.

![image](https://user-images.githubusercontent.com/15963/59969034-46f8f880-94f9-11e9-957f-a28649d72e48.png)
