### ISSUE TITLE
Button doesn't display correctly in Outlook desktop

### ISSUE THREAD

**Issue by mbrookson** [leemunroe/responsive-html-email-template#81]
![image](https://user-images.githubusercontent.com/20131783/46724265-8c2e1080-cc71-11e8-92af-f0494cc04d4c.png)

When opening in the browser it looks as intended, but in Outlook desktop the button doesn't have any height or background colour

**Comment by natescherer** [comment]
I was having the same issue, but switching to the inlined version fixed it.
