### ISSUE TITLE
Donations possible?

### ISSUE THREAD

**Issue by yagooar** [leemunroe/responsive-html-email-template#88]
Thanks a lot for creating this template. It has saved me a ton of time and a bit of money (and it works like a charm!), because so far I was looking to buy a template and then integrating it into my app.

If there's a way of donating a bit to the project - buy you a coffee maybe - I'll happily do. Let me know if and how I can send you the money.

**Comment by leemunroe** [comment]
@yagooar Great to hear! Appreciate that. No donation needed but a coffee or beer is always appreciated. I added a donate button to the [readme](https://github.com/leemunroe/responsive-html-email-template/blob/master/readme.md). Also if
