### ISSUE TITLE
Image width in Outlook 365 does not behave as expected

### ISSUE THREAD

**Issue by reed-lawrence** [leemunroe/responsive-html-email-template#91]
I'm not sure if this is a bug pertaining exactly to this library but I notice that it is in the CSS so I thought I would say something. 

Outlook seems to not like CSS styling of image widths/heights. My 1200px width PNG used as a heading image would display full size in outlook and would pull the rest of the container with it creating all sorts of styling issues. 

For images the only way to override this behavior seems to be to put the width as the HTML parameter rather than CSS styling. 

`<img src=".." width="300">`

**Comment by leemunroe** [comment]
Valid point. I usually have these attributes for images.

`<img src="" alt="" width="" height="" border="0" style="border:0; outline:none; text-decoration:none; display:block;">`

Would it be useful to include this in readme? It's something I reference in [this post](https://www.smashingmagazine.com/2017/01/introduction-building-sending-html-email-for-web-developers/).

**Comment by leemunroe** [comment]
Added a note to https://github.com/leemunroe/responsive-html-email-template/blob/master/readme.md
