### ISSUE TITLE
Doesn't display style property "basic HTML as default view"

### ISSUE THREAD

**Issue by anshul7negi** [leemunroe/responsive-html-email-template#95]
Hello there,
This template works fine when viewed in "Standard View of Gmail" but display only text when viewed in "Basic HTML View of Gmail"
Is there to preserve the style in Basic View of Gmail.

**Comment by leemunroe** [comment]
Hi can you share a screenshot and confirm you’re using the inlined CSS version? It will help me troubleshoot. Thanks.

**Comment by anshul7negi** [comment]
My apologies for the confusion, not using email inline template as I am new to this field. Now it works fine Thank You
